import type { PostBody } from '../blocks';

export const body: PostBody = [
  { type: 'p', text: 'If your garage door stopped moving this morning and the opener just hums or strains, there\'s a good chance you\'re dealing with a **broken garage door spring**. The springs are the part that does the heavy lifting, not the motor, so when one fails the whole door feels like a dead weight. The good news is that the warning signs are usually easy to spot once you know what to look for, and a fast repair gets you back to normal the same day.' },
  { type: 'p', text: 'Here are the five signs that point to a failed spring, plus a straight answer on why this particular repair belongs to a trained tech and not a weekend project.' },
  { type: 'h2', text: '1. A Loud Bang From the Garage' },
  { type: 'p', text: 'Most people notice a broken spring before they ever try to open the door. A loud bang from the garage, often described as a firecracker or a metal pipe hitting concrete, is the sound of a spring snapping under load. Springs store a huge amount of energy, so when the metal fatigues and lets go, that energy releases all at once. If you heard a sharp crack from the garage overnight and the door won\'t work the next morning, the two events are almost always connected.' },
  { type: 'h3', text: '2. The Door Won\'t Lift, or the Opener Strains' },
  { type: 'p', text: 'This is the sign homeowners report most. You press the button, the opener motor runs, and the door barely moves or lifts a couple inches and stops. Sometimes the opener pulls the top section up a few inches while the rest stays planted, leaving the panels bowed. That\'s because the opener is only built to guide the door, not carry its full weight. A residential door can weigh well over 150 pounds, and the springs are what offset that. When a garage door won\'t lift under its own power, a failed spring is the first thing to check.' },
  { type: 'callout', variant: 'warning', text: 'Do not keep pressing the opener button when the door won\'t move. Forcing a chain-drive or belt-drive opener to haul a full-weight door with no spring assist can burn out the motor, strip the gears, or bend the door track. One or two tries is understandable. Repeated attempts turn a single spring repair into two or three repairs.' },
  { type: 'h3', text: '3. A Visible Gap in the Spring Coil' },
  { type: 'p', text: 'You can often confirm the problem by looking. Most doors use a torsion spring, the tightly wound coil mounted on a metal shaft above the door opening. When it breaks, the coil separates and you\'ll see a distinct gap of an inch or two where the two ends pulled apart. On doors that use extension springs, the ones running parallel to the tracks along each side, a failure usually shows as a spring hanging loose or a snapped piece near the pulley. If the coil looks continuous and tight, the spring is likely intact and something else is going on.' },
  { type: 'image', file: 'image-copy-25.webp', alt: 'Garage door opener and spring hardware serviced by 4B Overhead Doors', caption: 'The torsion spring mounts on the shaft above the door and carries almost all of the door\'s weight.' },
  { type: 'h3', text: '4. The Door Is Crooked or Jerky' },
  { type: 'p', text: 'Doors that run on two extension springs can lose just one and keep limping along. When that happens, one side gets the assist and the other doesn\'t, so the door lifts unevenly, looks crooked in the opening, or jerks and binds against the tracks as it moves. A door that suddenly hangs at an angle or catches on one side is telling you the load is no longer balanced. Running it in that state puts strain on the cables, drums, and rollers, which is why it\'s worth stopping until it\'s looked at.' },
  { type: 'cta', text: 'Noticing any of these signs? Call 4B Overhead Doors at (940) 781-1186 for fast, same-area spring repair across the Wichita Falls region.' },
  { type: 'h3', text: '5. The Door Slams Shut or Feels Very Heavy by Hand' },
  { type: 'p', text: 'With a healthy spring, a door should be nearly weightless. You can pull the release cord, lift it by hand, and it should stay put wherever you leave it. When a spring is broken, two things happen. First, lifting it by hand feels like dead-lifting a loaded appliance. Second, if you do get it partway up and let go, it can drop and slam shut hard enough to hurt someone or damage the panels. Here\'s the quick manual test, done safely:' },
  { type: 'ol', items: ['With the door closed, pull the opener release cord to disconnect the motor.', 'Lift the door about four inches, then let go.', 'A balanced door holds that position. A door with a broken spring drops right back down or feels far too heavy to raise.', 'Set it back down gently and leave the opener disconnected until a tech arrives.'] },
  { type: 'h2', text: 'Why Spring Replacement Is a Pro Job' },
  { type: 'p', text: 'I\'ll be direct about this one. Torsion and extension springs are wound under extreme tension, and replacing them means controlling that energy with winding bars and the right technique. A spring that slips during the job can swing a bar or a hand at real force. This is the single repair where I tell homeowners not to try it themselves, no matter how many videos make it look simple. The parts cost is not where people get hurt. The tension is.' },
  { type: 'p', text: 'There\'s also a sizing detail most folks miss. Springs are matched to the exact weight and height of your door by wire size, coil diameter, and length. The wrong spring throws the balance off, wears the opener, and shortens the life of everything on the door. A pro measures the door and the old spring, then installs the correct match and rebalances the whole system.' },
  { type: 'ul', items: ['Springs are commonly rated around 10,000 cycles, which works out to roughly seven to ten years for an average household.', 'If one spring on a two-spring door broke, the other is usually close behind, so replacing both often saves a second trip.', 'A proper service includes checking the cables, drums, rollers, and door balance, not just swapping the spring.'] },
  { type: 'p', text: '4B Overhead Doors is family owned, fully insured, and prioritizes spring repairs because a broken spring leaves a garage stuck and often traps a vehicle inside. Owner-operator Colten Beaty and the team keep common torsion and extension springs on the truck so most repairs wrap up in one visit.' },
  { type: 'quote', text: 'A garage door that suddenly weighs 150 pounds isn\'t a broken opener. It\'s a spring, and it\'s the one repair worth calling in every time.' },
  { type: 'p', text: 'Because we are based in the Wichita Falls area, a broken spring in Wichita Falls, Vernon, Seymour, or Olney usually means same-day or next-day service. You can see the full list of towns we cover on our [service areas](/service-areas) page.' },
  { type: 'cta', text: 'Stuck door or a spring you can see is broken? Call 4B Overhead Doors at (940) 781-1186 and we\'ll get you moving again fast.' }
];
