/**
 * AUTO-GENERATED project labels for the Work gallery.
 * file -> { title, category, featured }. Category drives the filter chips;
 * featured drives the top carousel. Keyed by gallery filename (see manifest.ts).
 * Regenerate/edit by hand as photos change; must stay in sync with manifest.ts.
 */

export type ProjectCategory = "Residential" | "Commercial" | "Repair" | "Openers";

export interface ProjectMeta {
  file: string;
  title: string;
  category: ProjectCategory;
  featured: boolean;
}

export const PROJECTS: ReadonlyArray<ProjectMeta> = [
  { file: "image-copy.webp", title: "White Panel Two-Car Garage Doors", category: "Residential", featured: true },
  { file: "image.webp", title: "Black Rolling Steel Door", category: "Commercial", featured: false },
  { file: "image-copy-2.webp", title: "Black Double Panel Garage Door", category: "Residential", featured: true },
  { file: "image-copy-3.webp", title: "Brown Two-Car Panel Doors", category: "Residential", featured: true },
  { file: "image-copy-4.webp", title: "White Roll-Up Bay Doors", category: "Commercial", featured: false },
  { file: "image-copy-5.webp", title: "Open Shop Doors Ranch Interior", category: "Commercial", featured: false },
  { file: "image-copy-6.webp", title: "White Double Garage Doors", category: "Residential", featured: true },
  { file: "image-copy-8.webp", title: "Interior Steel Building Door", category: "Commercial", featured: false },
  { file: "image-copy-9.webp", title: "White Roll-Up Barn Door", category: "Commercial", featured: false },
  { file: "image-copy-10.webp", title: "Bronze Long-Panel Door With Windows", category: "Residential", featured: true },
  { file: "image-copy-12.webp", title: "Carriage-House Style Double Doors", category: "Residential", featured: true },
  { file: "image-copy-14.webp", title: "Two White Doors Brick Home", category: "Residential", featured: false },
  { file: "image-copy-15.webp", title: "Gray Two-Car Panel Doors", category: "Residential", featured: false },
  { file: "image-copy-17.webp", title: "Black Double Garage Doors", category: "Residential", featured: true },
  { file: "image-copy-19.webp", title: "White Short-Panel Garage Door", category: "Residential", featured: false },
  { file: "image-copy-20.webp", title: "Dark Steel Single Bay Door", category: "Commercial", featured: false },
  { file: "image-copy-21.webp", title: "White Door Metal Shop Install", category: "Commercial", featured: false },
  { file: "image-copy-22.webp", title: "Red-Trim Metal Building Doors", category: "Commercial", featured: false },
  { file: "image-copy-23.webp", title: "Red Steel Building Roll-Ups", category: "Commercial", featured: true },
  { file: "image-copy-24.webp", title: "Faux-Wood Carriage Shop Door", category: "Commercial", featured: true },
  { file: "image-copy-25.webp", title: "New Opener & Rail Install", category: "Openers", featured: false },
  { file: "image-copy-26.webp", title: "Two White Carport Doors", category: "Residential", featured: false },
  { file: "image-copy-27.webp", title: "Black Roll-Up Shop Door", category: "Commercial", featured: true },
  { file: "image-copy-28.webp", title: "Wide White Double Door", category: "Residential", featured: false },
  { file: "image-copy-29.webp", title: "Cedar-Look Barn Bay Doors", category: "Commercial", featured: true },
  { file: "image-copy-30.webp", title: "Charcoal Doors Metal Building", category: "Commercial", featured: true },
  { file: "image-copy-31.webp", title: "Interior Metal Shop Doors", category: "Commercial", featured: false },
  { file: "image-copy-32.webp", title: "Twin Charcoal Metal Shop Doors", category: "Commercial", featured: false },
  { file: "image-copy-33.webp", title: "Interior Metal Building Door", category: "Commercial", featured: false },
  { file: "image-copy-34.webp", title: "Black Roll-Up on Metal Barn", category: "Commercial", featured: false },
  { file: "image-copy-35.webp", title: "Tall White Interior Bay Door", category: "Commercial", featured: false },
  { file: "image-copy-36.webp", title: "Black Steel Shop Building", category: "Commercial", featured: true },
  { file: "image-copy-37.webp", title: "Cedar Wood-Look Double Door", category: "Residential", featured: true },
  { file: "image-copy-38.webp", title: "Bronze Single Panel Door", category: "Residential", featured: false },
  { file: "image-copy-39.webp", title: "Panel Replacement In Progress", category: "Repair", featured: false },
  { file: "image-copy-40.webp", title: "White Sectional Metal Garage", category: "Commercial", featured: false },
  { file: "image-copy-41.webp", title: "White Metal Garage Building", category: "Commercial", featured: false },
  { file: "image-copy-42.webp", title: "Almond Two-Car Panel Door", category: "Residential", featured: false },
  { file: "image-copy-43.webp", title: "White Single Garage Door", category: "Residential", featured: false },
  { file: "image-copy-44.webp", title: "Almond Two-Car Panel Door", category: "Residential", featured: true },
  { file: "image-copy-45.webp", title: "Two-Car Doors With Texas Star", category: "Residential", featured: false },
  { file: "image-copy-46.webp", title: "White Door Brick Garage", category: "Residential", featured: false },
  { file: "image-copy-47.webp", title: "Four-Bay White Roll-Up Doors", category: "Commercial", featured: false },
  { file: "image-copy-48.webp", title: "Open Steel Warehouse Bays", category: "Commercial", featured: false },
  { file: "image-copy-49.webp", title: "Interior Shop Bay Doors", category: "Commercial", featured: false },
  { file: "image-copy-50.webp", title: "Open-Bay Equipment Shed", category: "Commercial", featured: false },
  { file: "image-copy-51.webp", title: "White Rolling Shop Door", category: "Commercial", featured: false },
  { file: "image-copy-52.webp", title: "White Twin Carriage Doors", category: "Residential", featured: false },
  { file: "image-copy-53.webp", title: "Red Metal Shop Building", category: "Commercial", featured: false },
  { file: "image-copy-54.webp", title: "White Roll-Up on Red Barn", category: "Commercial", featured: false },
  { file: "image-copy-55.webp", title: "White Roll-Up Shop Door", category: "Commercial", featured: false },
  { file: "image-copy-56.webp", title: "Tall White Warehouse Door", category: "Commercial", featured: false },
  { file: "image-copy-57.webp", title: "Twin Metal Building Roll-Ups", category: "Commercial", featured: false },
  { file: "image-copy-58.webp", title: "Black Double Door on Barndominium", category: "Residential", featured: true },
  { file: "image-copy-59.webp", title: "White Roll-Up Tan Metal Building", category: "Commercial", featured: false },
  { file: "image-copy-60.webp", title: "White Commercial Bay Door", category: "Commercial", featured: false },
  { file: "image-copy-61.webp", title: "Three Dark Bay Doors", category: "Commercial", featured: false },
  { file: "image-copy-62.webp", title: "Gray Interior Roll-Up Door", category: "Commercial", featured: false },
  { file: "image-copy-63.webp", title: "Gray Interior Roll-Up Door", category: "Commercial", featured: false },
  { file: "image-copy-64.webp", title: "Gray Roll-Up Show Barn Door", category: "Commercial", featured: false },
  { file: "image-copy-65.webp", title: "Two-Bay Metal Shop Building", category: "Commercial", featured: true },
  { file: "image-copy-66.webp", title: "Tan Wood-Look Garage Door", category: "Residential", featured: true },
  { file: "image-copy-67.webp", title: "Woodgrain Carriage Shop Door", category: "Commercial", featured: true },
  { file: "image-copy-68.webp", title: "Black Two-Car Stone Home Doors", category: "Residential", featured: false },
  { file: "image-copy-69.webp", title: "Storage Unit Roll-Up Doors", category: "Commercial", featured: false },
  { file: "image-copy-70.webp", title: "White Carriage Doors Brick Home", category: "Residential", featured: false },
  { file: "image-copy-71.webp", title: "Three Black Garage Doors", category: "Residential", featured: false },
  { file: "image-copy-72.webp", title: "Tall White Warehouse Door", category: "Commercial", featured: false },
  { file: "image-copy-73.webp", title: "White Interior Sectional Door", category: "Commercial", featured: false },
  { file: "image-copy-74.webp", title: "White Roll-Up Interior Install", category: "Commercial", featured: false },
  { file: "image-copy-75.webp", title: "Interior Bay Door Install", category: "Commercial", featured: false },
  { file: "image-copy-76.webp", title: "Two White Doors Stucco Garage", category: "Residential", featured: false },
  { file: "image-copy-77.webp", title: "Brown Three-Car Brick Garage", category: "Residential", featured: false },
  { file: "image-copy-78.webp", title: "Tan Two-Car Craftsman Door", category: "Residential", featured: false },
  { file: "image-copy-79.webp", title: "Black Two-Car Door White House", category: "Residential", featured: true },
  { file: "image-copy-80.webp", title: "Classic Cream Double Garage Doors", category: "Residential", featured: false },
  { file: "image-copy-81.webp", title: "Cream Doors With Windows", category: "Residential", featured: true },
  { file: "image-copy-82.webp", title: "White Double Door Brick Home", category: "Residential", featured: false },
  { file: "image-copy-83.webp", title: "Black Roll-Up Shop Door", category: "Commercial", featured: false },
  { file: "image-copy-84.webp", title: "Dark Gray Double Shop Doors", category: "Commercial", featured: true },
  { file: "image-copy-85.webp", title: "Gray Steel Door Metal Building", category: "Commercial", featured: false },
];
